### PR TITLE
DataFrame.join on key column

### PR DESCRIPTION
**Pull request by xinrong-databricks**
pandas support join using the on parameter when the`on` column is not the index of any sides (`self` and `right`). 

### pandas
```
>>> pdf1 = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> pdf2 = pd.DataFrame({"B": [11, 12, 13], "C": [14, 15, 16]})
>>> pdf1.join(pdf2, on='B', lsuffix='_left')
   A  B_left   B   C
0  1       4 NaN NaN
1  2       5 NaN NaN
2  3       6 NaN NaN
```

### Koalas (ref #2002)
```
>>> kdf1 = ks.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> kdf2 = ks.DataFrame({"B": [11, 12, 13], "C": [14, 15, 16]})
>>> kdf1.join(kdf2, on='B', lsuffix='_left')
Traceback (most recent call last):
...
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Reference 'B' is ambiguous, could be: right_table.B, B.;
```

We wanted to match pandas behavior in this case. 

However pandas behavior is not consistent with how join works in the SQL context, especially right join and outer join. This PR proposes for left join and inner join only.

Reference:
https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#joining-key-columns-on-an-index

### CODE REVIEW

**Comment by itholic** [comment]
Can we have a simple example what we target to fix in the PR description ??  😺

**Comment by xinrong-databricks** [comment]
@itholic Added examples to pr description! Though I haven't decided a good title yet.

**Comment by xinrong-databricks** [comment]
So far, koalas and pandas behavior differences:

## right
```
>>> pdf1.join(pdf2, on='B', lsuffix='_left', how='right')
      A  B_left  B   C
NaN NaN     NaN  0  14
NaN NaN     NaN  1  15
NaN NaN     NaN  2  16

>>> kdf1.join(kdf2, on='B', lsuffix='_left', how='right')
        A B_left   B   C
NaN  None   None  11  14
NaN  None   None  12  15
NaN  None   None  13  16
```

## outer
```
>>> pdf1.join(pdf2, on='B', lsuffix='_left', how='outer')
       A  B_left  B     C
0.0  1.0     4.0  4   NaN
1.0  2.0     5.0  5   NaN
2.0  3.0     6.0  6   NaN
NaN  NaN     NaN  0  14.0
NaN  NaN     NaN  1  15.0
NaN  NaN     NaN  2  16.0

       A  B_left     B     C
NaN  NaN     NaN  11.0  14.0
2.0  3.0     6.0   NaN   NaN
1.0  2.0     5.0   NaN   NaN
NaN  NaN     NaN  12.0  15.0
NaN  NaN     NaN  13.0  16.0
0.0  1.0     4.0   NaN   NaN
```

**Comment by xinrong-databricks** [comment]
@ueshin @HyukjinKwon @itholic Would you help confirm pandas behaviors is correct? Column `B` in pandas results seems weird to me.

**Comment by ueshin** [comment]
The index of the right dataframe is used to join.

```py
>>> pdf1 = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> pdf2 = pd.DataFrame({"B": [11, 12, 13], "C": [14, 15, 16]}, index=[2,3,4])
>>> pdf1
   A  B
0  1  4
1  2  5
2  3  6
>>> pdf2
    B   C
2  11  14
3  12  15
4  13  16

>>> pdf1.join(pdf2, on='B', lsuffix='_left')
   A  B_left     B     C
0  1       4  13.0  16.0
1  2       5   NaN   NaN
2  3       6   NaN   NaN
>>> pdf1.join(pdf2, on='B', lsuffix='_left', how='right')
       A  B_left   B   C
0.0  1.0     4.0  13  16
NaN  NaN     NaN   2  14
NaN  NaN     NaN   3  15
>>> pdf1.join(pdf2, on='B', lsuffix='_left', how='outer')
       A  B_left  B     C
0.0  1.0     4.0  4  16.0
1.0  2.0     5.0  5   NaN
2.0  3.0     6.0  6   NaN
NaN  NaN     NaN  2  14.0
NaN  NaN     NaN  3  15.0
```

The case for `how='outer'` still seems weird, though..

**Comment by xinrong-databricks** [comment]
```
>>> kdf1 = ks.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> kdf2 = ks.DataFrame({"B": [11, 12, 13], "C": [14, 15, 16]}, index=[2,3,4])
>>> kdf1
   A  B
0  1  4
1  2  5
2  3  6
>>> kdf2
    B   C
2  11  14
3  12  15
4  13  16
>>> kdf1.join(kdf2, on='B', lsuffix='_left') # match pandas'
   A  B_left     B     C
2  3       6   NaN   NaN
1  2       5   NaN   NaN
0  1       4  13.0  16.0
>>> kdf1.join(kdf2, on='B', lsuffix='_left', how='right') # doesn't match pandas', but seems fair
       A  B_left   B   C
NaN  NaN     NaN  12  15
NaN  NaN     NaN  11  14
0.0  1.0     4.0  13  16
>>> kdf1.join(kdf2, on='B', lsuffix='_left', how='outer') # doesn't match pandas', but seems fair
       A  B_left     B     C
2.0  3.0     6.0   NaN   NaN
1.0  2.0     5.0   NaN   NaN
NaN  NaN     NaN  12.0  15.0
NaN  NaN     NaN  11.0  14.0
0.0  1.0     4.0  13.0  16.0
```

**Pull request closed without merging**
