### PR TITLE
add a parameter to know if agg columns is None

### PR DESCRIPTION
**Pull request by RainFung**
add a parameter to know if agg columns is None

### CODE REVIEW

**Comment by RainFung** [comment]
@HyukjinKwon Can you merge this to this problem? https://github.com/databricks/koalas/issues/608

**Comment by ueshin** [comment]
@RainFung Could you include this in your actual PR?
I'm not sure how you want to use this parameter and I can't know whether this is reasonable or not.

**Comment by RainFung** [comment]
> @RainFung Could you include this in your actual PR?
> I'm not sure how you want to use this parameter and I can't know whether this is reasonable or not.

https://github.com/databricks/koalas/pull/617

**Comment by HyukjinKwon** [comment]
Let's leave this closed then.

**Pull request closed without merging**
