### PR TITLE
Implementing Series.droplevel

### LINKED ISSUE #1615: Series.droplevel
Implement `Series.droplevel`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.droplevel.html

### PR DESCRIPTION
**Pull request by itholic**
This should close #1615 

```python
>>> kser = ks.Series(
...     [1, 2, 3],
...     index=pd.MultiIndex.from_tuples(
...         [("x", "a"), ("x", "b"), ("y", "c")], names=["level_1", "level_2"]
...     ),
... )
>>> kser
level_1  level_2
x        a          1
         b          2
y        c          3
Name: 0, dtype: int64
```

Removing specific index level by level

```python
>>> kser.droplevel(0)
level_2
a    1
b    2
c    3
Name: 0, dtype: int64
```

Removing specific index level by name

```python
>>> kser.droplevel("level_2")
level_1
x    1
x    2
y    3
Name: 0, dtype: int64
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Let's combine and address the leftover issues here @itholic

**Comment by itholic** [comment]
@HyukjinKwon I got it! Thanks for the notice

**Comment by itholic** [comment]
I think this PR ready to get review.

**Comment by itholic** [comment]
Thanks, @ueshin. I'll manage things that you pointed out.

**Comment by ueshin** [comment]
Thanks! merging.

**Pull request merged**
