### PR TITLE
[WIP] DataFrame/Series.describe

### LINKED ISSUE #334: DataFrame/Series.describe()
pandas version: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html

This is a very useful function for understanding the dataset. Note that Spark already has a describe that does similar things. A simple version of Koalas' describe can just delegate to Spark's. A fancier version should construct the descriptive stats and then match more pandas'.

### PR DESCRIPTION
**Pull request by garawalid**
This PR adds `DataFrame.describe()` and `Series.describe()`.
Resolves #334.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Nice @garawalid! +1 !

**Comment by ueshin** [comment]
Hi @garawalid, I took over this at #375.

**Comment by HyukjinKwon** [comment]
@garawalid, btw, the current version isn't complete yet. Please go ahead for a followup to make it complete if you have some work that have already been done in your local.

**Comment by garawalid** [comment]
Thanks @ueshin, @HyukjinKwon. 

@HyukjinKwon I agree, I'm working on it, I'll update the actual one in a different PR. I'm expecting to have the same output as proposed in pandas.

**Pull request closed without merging**
