### PR TITLE
Added Apache 2.0 license badge

### PR DESCRIPTION
**Pull request by itholic**
We can have Apache 2.0 license badge :D

스크린샷 2020-09-26 오후 4 27 59

### CODE REVIEW

**Comment by itholic** [comment]
[License](https://opensource.org/licenses/Apache-2.0) Added!

**Comment by HyukjinKwon** [comment]
Let's don't bother to add this, actually. This is shown in the repo and I think there's not much point of emphasising it.

**Comment by HyukjinKwon** [comment]
Screen Shot 2020-09-27 at 4 28 46 PM

**Comment by itholic** [comment]
Oh, I got it. Actually it was just inspired by `mlflow` repo. 😅

**Comment by HyukjinKwon** [comment]
Probably mlflow added it when GitHub introduced the feature to show the license in the repo.

**Pull request merged**
