### PR TITLE
Use OpenJDK instead of OracleJDK in Binder

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR proposes to use OpenJDK instead. Current Oracle JDK download with `wget` is broken:

    ```
    --2020-12-14 08:16:14--  http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
    Resolving download.oracle.com (download.oracle.com)... 184.50.116.99
    Connecting to download.oracle.com (download.oracle.com)|184.50.116.99|:80... connected.
    HTTP request sent, awaiting response... 302 Moved Temporarily
    Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz [following]
    --2020-12-14 08:16:14--  https://edelivery.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
    Resolving edelivery.oracle.com (edelivery.oracle.com)... 2.17.191.76, 2a02:26f0:1700:58b::366, 2a02:26f0:1700:591::366
    Connecting to edelivery.oracle.com (edelivery.oracle.com)|2.17.191.76|:443... connected.
    HTTP request sent, awaiting response... 403 Forbidden
    2020-12-14 08:20:14 ERROR 403: Forbidden.

    tar (child): jdk-8u131-linux-x64.tar.gz: Cannot open: No such file or directory
    tar (child): Error is not recoverable: exiting now
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now
    ./postBuild: line 9: cd: jdk1.8.0_131: No such file or directory
    ./postBuild: line 11: cd: bin: No such file or directory
    ```

This was tested in https://mybinder.org/v2/gh/hyukjinkwon/koalas/fix-binder?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb

Apache Spark uses the same approach as well:

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Current Binder is broken because of this. I'll just merge this in to recover.

**Comment by HyukjinKwon** [comment]
cc @ueshin @itholic @xinrong-databricks FYI

**Comment by itholic** [comment]
Nice

**Comment by xinrong-databricks** [comment]
Great thanks!

**Pull request merged**
