### PR TITLE
10 minutes to Pandas tutorial using Koala + Spark, incomplete

### PR DESCRIPTION
**Pull request by thunterdb**
This is the start of the translation of the basic tutorial on pandas called 10 minutes to pandas, available here:

This tutorial is extensive, so I think it should be focus on the 'easy' sections that are already implemented, and add later the 'hard' sections as they get implemented.

### CODE REVIEW

**Comment by thunterdb** [comment]
This notebook is currently too big, and does not even render on github. I am going to break it into multiple sections to help with contributions.

**Comment by garawalid** [comment]
@thunterdb  I'll join you !

**Comment by thunterdb** [comment]
@garawalid please be my guest. Let us focus on the first part, up to and including 'Viewing the data'. I hope that this is small enough that it can be easily rendered in github and sphinx.

This was written before the refactoring in #90 , so there are a few things to watch for:
 - it should follow now the import best practices `import databricks.koalas as ks`
 - it does not need to refer to spark as prominently, most of the calls to the spark context are automated now

There will be probably some other comments so I suggest to start small first and build up from there. You should branch off from here and open a separate pull request. 

Thanks a lot!

**Comment by dennyglee** [comment]
Glad you're helping out @garawalid - glad to help with it as well.  Please do not hesitate to ping me and I can work with your branch to update the tutorial.  HTH!

**Comment by garawalid** [comment]
@dennyglee 
With pleasure! Just give me three days, I need to finish with data sanitization for `isna` and `fillna` and then we can start !

**Comment by dennyglee** [comment]
Cool stuff - looking forward to it, eh?!

**Comment by shril** [comment]
@thunterdb, @garawalid Can I also join this?

**Comment by garawalid** [comment]
@shril 
Sure. We are working in this PR #196. You can open a PR in this [repo](https://github.com/garawalid/koalas/tree/tutorial) tutorial branch. 
We will update the #196 later.

**Comment by HyukjinKwon** [comment]
It's merged at https://github.com/databricks/koalas/commit/d8c7f73b88ad84f28dd69d5687b847654af4b04e

**Pull request closed without merging**
