### PR TITLE
Edit some wordings in README.md and change logo's location

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Before:

Screen Shot 2019-10-04 at 2 43 52 PM

After:

Screen Shot 2019-10-04 at 2 43 37 PM

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
@gioa WDYT?

**Comment by HyukjinKwon** [comment]
it mimics https://github.com/twbs/bootstrap/blob/master/README.md actually.

**Comment by gioa** [comment]
lgtm!

**Comment by HyukjinKwon** [comment]
Thanks @gioa!

**Comment by HyukjinKwon** [comment]
I checked it on PyPi too:
Screen Shot 2019-10-05 at 9 57 48 AM

Merged!

**Pull request merged**
