### PR TITLE
Inline doc for DataFrame.pipe

### PR DESCRIPTION
**Pull request by nitlev**
This PR has inline documentation for the `koalas.DataFrame.pipe` method.
Feedbacks are welcome :-)

### CODE REVIEW

**Comment by nitlev** [comment]
Hmmm looks like the current doctests are not deterministic. I'll fix that.

**Comment by rxin** [comment]
@nitlev do you think this is good to go now?

**Comment by nitlev** [comment]
@rxin yes it should be fine now

**Comment by rxin** [comment]
Thanks. Merging.

**Pull request merged**
