### PR TITLE
ENH: Add barh plot for DataFrame

### PR DESCRIPTION
**Pull request by charlesdong1991**
kdf and pdf with specified x and y:

Screen Shot 2019-08-26 at 10 44 59 PM

Screen Shot 2019-08-26 at 10 49 49 PM

kdf and pdf without specified x and y:
Screen Shot 2019-08-26 at 10 46 31 PM

Screen Shot 2019-08-26 at 10 45 22 PM

### CODE REVIEW

**Comment by charlesdong1991** [comment]
cannot figure out how to resolve codecov issue. 😥

**Comment by HyukjinKwon** [comment]
It's okay. codecov sometimes looks a bit dumb.

**Comment by charlesdong1991** [comment]
i resolved conflicts, but not sure why this error happens? could you please take a look at CI? @HyukjinKwon 
error is :
```
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/main/binary-i386/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by charlesdong1991** [comment]
Conflicts are resolved. Let's see if everything can pass. @HyukjinKwon 

I think I also need to resolve conflict for another PR once this is merged, so let me do it one by one.

**Comment by HyukjinKwon** [comment]
Thanks, merged to master.

**Pull request merged**
