### PR TITLE
10-minute tutorial with Koalas with a live notebook to try out

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR takes over https://github.com/databricks/koalas/pull/34 and https://github.com/databricks/koalas/pull/196

This PR also adds an integration with [Binder](https://mybinder.org/) which provides a docker based Jupyter notebook against the repository branch right way.

You can try this by clicking this [Binder](https://mybinder.org/v2/gh/databricks/koalas/tutorial?filepath=docs%2F10-minutes-to-Koalas.ipynb) - seems it can take up to around 5+ mins for the initial launch to prepare due to heavy dependencies like PySpark and Java installation (which seems not built-in).

Screen Shot 2019-09-29 at 3 50 26 PM

_As a bonus_, `pandoc` seems supporting the conversion from Jupyter files to RST files. So, I might be able to generate documentation from this file and add it to our official documentation (based upon https://github.com/databricks/koalas/pull/842)

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I need to proof-read one more time. Will do it soon within few days but I would appreciate if you guys have some feedback.

**Comment by itholic** [comment]
@HyukjinKwon , It looks great work. and i took a look at this and fix some typos or codes (almost for keep convention), and add some contents  `Plotting`, and `Getting data in/out`.

**Comment by HyukjinKwon** [comment]
Thx, let me push it first and clean up.

**Comment by gatorsmile** [comment]
This is great!

**Comment by ueshin** [comment]
This is great!

In the Jupyter notebook, 
- `Pandas` -> `pandas`
- The explanation below `In[1]` is not right now.
- We don't need `>>> ` and `... ` in each command
- I'd prefer `ks.from_pandas(pdf)` to `ks.DataFrame(pdf)` (`In[10]`, `In[48]`)
- `ks.DataFrame(sdf)` -> `sdf.to_koalas()` might be better? (`In[16]`)

**Comment by HyukjinKwon** [comment]
Nice. Will address them soon. For `>>>` and `...` I added them for the case we reuse it for our doc. Otherwise it cannot distinguish codes and output :).

**Comment by HyukjinKwon** [comment]
Let me merge this given many positive feedback in general - the last change was only README.md change. I will commit each to credit properly.

I will still have to touch this file in a separate PR to generate this file as the official documentation. I can handle some more comments here if you guys have some.

**Pull request closed without merging**
