### PR TITLE
Rename Internal.data_columns after arithmetic operations for IndexOpsMixin

### PR DESCRIPTION
**Pull request by itholic**
As mentioned at https://github.com/databricks/koalas/pull/1224#discussion_r370971017,

this PR for renaming `Internal.data_spark_column_names` for `IndexOpsMixin` (Index & Series) after arithmetic operations are done.

of course we should have more discussion about this, but i think we better to rename after those operations to avoid confusing when we develop or use some API with `_InternalFrame`.

### CODE REVIEW

**Comment by itholic** [comment]
For some operators with `r` prefix like `rsub`, `rfloordiv`,

i think it is better to fix after solving the existing bug(#1235) related with them.

**Comment by itholic** [comment]
ah, this stuck on test cases added from #1233 .
let me fix it. 😅

**Comment by HyukjinKwon** [comment]
@itholic can you rebase?

**Comment by itholic** [comment]
Closing this for now since we can't handle below if the name is changed.

```python
>>> pdf = pd.DataFrame(
...             {
...                 "a": [1, 2, 6, 4, 4, 6, 4, 3, 7],
...                 "b": [4, 2, 7, 3, 3, 1, 1, 1, 2],
...                 "c": [4, 2, 7, 3, None, 1, 1, 1, 2],
...                 "d": list("abcdefght"),
...             },
...             index=[0, 1, 3, 5, 6, 8, 9, 9, 9],
...         )
>>> kdf = ks.from_pandas(pdf)
>>> (kdf.b + 1).groupby(kdf.b).sum()
Traceback (most recent call last):
pyspark.sql.utils.AnalysisException: "Reference 'b' is ambiguous, could be: b, b.;"
```

**Pull request closed without merging**
