### PR TITLE
Create docstring for ``DataFrameGroupBy.describe`` and reimplement leveraging `_InternalFrame`

### LINKED ISSUE #1166: DataFrameGroupBy.describe

### PR DESCRIPTION
**Pull request by deepyaman**
Close #1166

### CODE REVIEW

**Comment by deepyaman** [comment]
Honestly not sure what's wrong here. :( I've tried many variations locally, including fixing the whitespace for a line myself, but it doesn't seem to work... (or I'm overlooking something stupid)

```python3
=================================== FAILURES ===================================
________ [doctest] databricks.koalas.groupby.DataFrameGroupBy.describe _________
194            a  b  c
195         0  1  4  7
196         1  1  5  8
197         2  3  6  9
198 
199         Describing a ``DataFrame``. By default only numeric fields
200         are returned.
201 
202         >>> described = df.groupby('a').describe()
203         >>> described  # doctest: +NORMALIZE_WHITESPACE
Differences (unified diff with -expected +actual):
    @@ -1,5 +1,5 @@
    -      b                                        c
    -  count mean       std min 25% 50% 75% max count mean       std min 25% 50% 75% max
    -a
    -1   2.0  4.5  0.707107 4.0 4.0 4.0 5.0 5.0   2.0  7.5  0.707107 7.0 7.0 7.0 8.0 8.0
    -3   1.0  6.0       NaN 6.0 6.0 4.0 6.0 6.0   1.0  9.0       NaN 9.0 9.0 9.0 9.0 9.0
    +      b                                             c
    +  count mean       std  min  25%  50%  75%  max count mean       std  min  25%  50%  75%  max
    +a
    +1   2.0  4.5  0.707107  4.0  4.0  4.0  5.0  5.0   2.0  7.5  0.707107  7.0  7.0  7.0  8.0  8.0
    +3   1.0  6.0       NaN  6.0  6.0  6.0  6.0  6.0   1.0  9.0       NaN  9.0  9.0  9.0  9.0  9.0
/home/travis/build/databricks/koalas/databricks/koalas/groupby.py:203: DocTestFailure
```

**Comment by deepyaman** [comment]
@itholic @HyukjinKwon I believe this is ready, except the doctest issue I haven't yet been able to figure out. I wasn't able to use `name_like_string` as in https://github.com/databricks/koalas/pull/1168#discussion_r365682096; the underlying columns are like `('b', 'count')`, not `(b, count)`. I think this is similar to how `agg` is implemented, anyway.

**Comment by itholic** [comment]
Shall we add some test to `tests/test_dataframe.py` for checking if the result of `ks.DataFrame.describe()` is same with `pd.DataFrame.describe()` like the below?

```python
    def test_describe(self):
        pdf = self.pdf
        kdf = ks.from_pandas(pdf)

        self.assert_eq(pdf, kdf)
```

**Comment by HyukjinKwon** [comment]
Release is being close. I will just merge. @itholic, do you have some time to add the test and double check the PR?

**Comment by itholic** [comment]
@HyukjinKwon okay i'll manage this until tomorrow

**Pull request merged**
