### PR TITLE
[MINOR] Fix typos in frame.py

### PR DESCRIPTION
**Pull request by beobest2**
Fixed typo in `frame.py`

### CODE REVIEW

**Comment by itholic** [comment]
LGTM

**Comment by HyukjinKwon** [comment]
@beobest2 while we're here can you take another look for this file and see if there are some more typos?

**Comment by beobest2** [comment]
> while we're here can you take another look for this file and see if there are some more typos?

sure! Let me check if there are other typos.

**Comment by beobest2** [comment]
@HyukjinKwon 
The entire file has been reviewed. I'm pretty sure there will be no more typos.

**Pull request merged**
