### PR TITLE
Koalas Jupyter Notebook sample

### PR DESCRIPTION
**Pull request by dennyglee**
An initial Koalas Jupyter notebook sample, cc @thunterdb

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hey @dennyglee, how is [Binder](https://mybinder.org/v2/gh/databricks/koalas/master?filepath=docs%2F10-minutes-to-Koalas.ipynb)? do you like it enough?

**Comment by dennyglee** [comment]
@HyukjinKwon - oh this is awesome!  Great call! :)

**Comment by HyukjinKwon** [comment]
Thanks :D do you think we should better close this PR? or add some more samples?

**Comment by dennyglee** [comment]
The idea was that this was a jump start notebook to just get people
started.  I can certainly add more samples if you like?

**Comment by HyukjinKwon** [comment]
Can you check this is [Binder](https://mybinder.org/v2/gh/databricks/koalas/master?filepath=docs%2F10-minutes-to-Koalas.ipynb) and if the examples look enough to you? This 10 minutes to Koalas will be a part of our public documentation.

If you meant something like a quickstart, that sounds good to me too. We might have to replace this https://github.com/databricks/koalas/blob/master/docs/source/quickstart.rst to the ipynb file if you like to write :)

**Comment by HyukjinKwon** [comment]
It's now in the doc! https://koalas.readthedocs.io/en/latest/getting_started/10min.html

**Comment by dennyglee** [comment]
Excellent!  Okay, why don't we close this PR and I can help update the
quickstart, eh!?

**Comment by HyukjinKwon** [comment]
Awesome!

**Pull request closed without merging**
