### PR TITLE
cache implementation in databricks.koalas namespace

### PR DESCRIPTION
**Pull request by shril**
PR #333

### CODE REVIEW

**Comment by shril** [comment]
@HyukjinKwon, can you please help me out here?
The build is failing in some update statement - 

```
The command "sudo apt-get update" failed and exited with 100 during .
```

**Comment by HyukjinKwon** [comment]
I retriggered the job but actually I was thinking about avoiding to add it into name space. Let's get the dataframe one first.

**Comment by shril** [comment]
Hi @HyukjinKwon, the dataframe one is done.
Will we proceed with this one too or will we just go with the dataframe one?

@rxin can we have your insights here?

**Comment by HyukjinKwon** [comment]
Let's get https://github.com/databricks/koalas/pull/397 in first anyway.

**Comment by shril** [comment]
@HyukjinKwon, I am okay with either of them.

**Comment by shril** [comment]
@ueshin Can you have a look here also?

**Comment by ueshin** [comment]
Actually I don't think we still need this if `df.cache()` can work with `with` as @HyukjinKwon suggested.

**Comment by HyukjinKwon** [comment]
Let's close this for now. I think `df.cache()` with context manager is powerful enough.

**Pull request closed without merging**
