### PR TITLE
Add conda instruction.

### PR DESCRIPTION
**Pull request by ueshin**
Now that Koalas is listed on the conda-forge repository.
This PR adds the instruction to install Koalas by conda.

### CODE REVIEW

**Comment by ueshin** [comment]
Actually the mirror sync on conda-forge is not working now so `conda install koalas` does not work yet.
Let's wait until the mirror sync is fixed.

**Comment by HyukjinKwon** [comment]
nice !

**Comment by ueshin** [comment]
The mirror sync was fixed.

**Comment by ueshin** [comment]
merging to master.

**Pull request merged**
