### PR TITLE
Add datetime as the equivalent python type to TimestampType

### LINKED ISSUE #951: `datetime.datetime` is not recognized as the equivalent python type to `types.TimestampType()`
Actually, this isn't an issue. I was looking for a workaround for [this comment](https://github.com/databricks/koalas/pull/478#issuecomment-545888595), wrote the code below and got `ValueError`.

```python
import databricks.koalas as ks
from datetime import datetime, timedelta

def tomorrow(date) -> datetime:
    return date + timedelta(days=1)

test_df = ks.DataFrame([(datetime(2019, 10, 24))], columns=['date'])
test_df['date'] = test_df['date'].map(tomorrow)

>>> test_df
...
ValueError: Invalid returnType: returnType can not be None
```

The cause is that `datetime.datetime` is not recognized as the equivalent python type to `types.TimestampType()`.

```python
_base = {
    types.StringType(): [str, 'str', 'string'],
    types.BinaryType(): [bytes],
    types.ByteType(): [np.int8, 'int8', 'byte'],
    types.ShortType(): [np.int16, 'int16', 'short'],
    types.IntegerType(): [int, 'int', np.int, np.int32],
    types.LongType(): [np.int64, 'int64', 'long', 'bigint'],
    types.FloatType(): [float, 'float', np.float],
    types.DoubleType(): [np.float64, 'float64', 'double'],

    types.TimestampType(): [np.datetime64],  # <- should be included here.

    types.DateType(): [datetime.date],
    types.BooleanType(): [bool, 'boolean', 'bool', np.bool],
    types.ArrayType(types.StringType()): []
}
```
https://github.com/databricks/koalas/blob/master/databricks/koalas/typedef.py#L112

I think `datetime.datetime` should be included in `types.TimestampType()`.

@ueshin @HyukjinKwon What do you think?

### PR DESCRIPTION
**Pull request by harupy**
Resolves #951

### CODE REVIEW

**Comment by harupy** [comment]
Do I need to write a test?

**Comment by itholic** [comment]
@harupy i'm not sure but maybe it should be better in terms of usecase example? :smile_cat:

**Comment by harupy** [comment]
@itholic Thanks for the comment. I'll wait for them.

**Comment by harupy** [comment]
@HyukjinKwon Ok, I'll add a test.

**Comment by harupy** [comment]
I'm thinking of adding the following code to `test_map` in `test_series.py`.

```python
def tomorrow(date) -> datetime:
    return date + timedelta(days=1)

test_df = ks.DataFrame([datetime(2019, 10, 24)], columns=['date'])
test_df['date'] = test_df['date'].map(tomorrow)
```

**Comment by HyukjinKwon** [comment]
Sounds good!

**Comment by harupy** [comment]
@HyukjinKwon test passed

**Comment by HyukjinKwon** [comment]
Thanks, @harupy

**Pull request merged**
