### PR TITLE
Remove the sentences about the project being beta

### PR DESCRIPTION
**Pull request by HyukjinKwon**
Koalas 1.0.0 will be released very soon.

### CODE REVIEW

**Comment by itholic** [comment]
LGTM, but how about merge this right after 1.0.0 will be actually released ??

**Comment by HyukjinKwon** [comment]
No the changes here should be involved in the 1.0.0 documentation

**Comment by itholic** [comment]
Got it!

**Comment by HyukjinKwon** [comment]
I am merging this to unblock the release.

**Pull request merged**
