### PR TITLE
TST: Add sanity checks for some series plot

### PR DESCRIPTION
**Pull request by charlesdong1991**
I came across `test_series_plot.py` and saw the existing plots might lack sanity check.
e.g. if a test `s.plot.line()` is added, I think it's also good to have sanity check to see if `s.plot(kind='line')` outputs the correct fig (in principle, it of course should).

The plots I added are: `line`, `bar`, `hist` and `pie`.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
What does TST stand for BTW :D?

**Comment by HyukjinKwon** [comment]
@itholic, BTW you can start to work on such missing test coverage too.

**Comment by itholic** [comment]
@HyukjinKwon Thanks Hyukjin, I'll try it from today, and share it when the results come out! :)

**Comment by itholic** [comment]
@HyukjinKwon Thanks Hyukjin, I'll try and share it when the results come out! :)

**Comment by charlesdong1991** [comment]
> What does TST stand for BTW :D?

it was short for test xD, just wanna intuitively show this PR is just test fix.

**Pull request merged**
