### PR TITLE
Let's use 'kser' rather than 'ks' or 's' as variable name for Series 

### PR DESCRIPTION
**Pull request by itholic**
Since the `ks` is used as koalas' import naming convention we recommended like `from databricks.koalas as ks`

Let's don't use `ks` as variable name for Series, use `kser` instead for unity & readability of our codes and to avoid confusing.

Plus, i think maybe we better also avoid using of just `s` as possible for more readability.

### CODE REVIEW

**Comment by itholic** [comment]
@ueshin @HyukjinKwon Could you please let me know your opinion after confirm this PR when you guys available? 😄

**Comment by ueshin** [comment]
Shall we fix some more?
- `frame.py`: There are two `for name, ks in kdf.iteritems():`
- `test_dataframe.py`: There are some `right_ks`.

**Comment by itholic** [comment]
@ueshin, @HyukjinKwon  Thanks for the comment! i just fix the missing ones.

**Comment by ueshin** [comment]
Shall we fix too?

> `test_dataframe.py`: There are some `right_ks`.

**Comment by itholic** [comment]
@ueshin Thanks for finding! :)

**Comment by HyukjinKwon** [comment]
Merged to master.

**Pull request merged**
