### PR TITLE
Fix minor typos at '_make_missing_functions.py' and 'env_setup.sh'

### PR DESCRIPTION
**Pull request by itholic**
This PR fixes typos at  '_make_missing_functions.py' and 'env_setup.sh'

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Can you check if there are more types while we're here?

**Comment by leehaejoon** [comment]
@HyukjinKwon Sure, i'll check and add to this PR

**Comment by itholic** [comment]
@HyukjinKwon Sure, i'll check and add to this PR if they exists.

**Comment by HyukjinKwon** [comment]
@harupy, BTW, please feel free to open test only or minor typos if you happen to find. It's legitimate to fix and merge such PRs like this.

**Pull request merged**
