### PR TITLE
Cleanups to groupy

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This simplifies somewhat the calls to `GroupBy`.

Closes #225

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
It says no for coverage decrease .. which I don't think it's quite true :D.

**Comment by thunterdb** [comment]
@HyukjinKwon there is an escape hatch:
https://coverage.readthedocs.io/en/coverage-4.2/excluding.html

THis way you can exclude some of the `else` conditions that are errors anyway

**Comment by HyukjinKwon** [comment]
oh, I see. I will do that. BTW, I think another reason why it says coverage is decreased is the amount of codes at `generic.py` was reduced:

> databricks/koalas/generic.py | 95% <87.5%> (-3.31%)

I think it complains spuriously anyway.

**Comment by HyukjinKwon** [comment]
@thunterdb, let me get this in but please let me know if there are more to be done. I will fix it right away.

**Comment by thunterdb** [comment]
This is great, thank you!

**Pull request merged**
