### PR TITLE
Disable to_clipboard tests.

### PR DESCRIPTION
**Pull request by ueshin**
The test `databricks/koalas/tests/test_dataframe_conversion.py::DataFrameConversionTest::test_to_clipboard` came to fail for some reason.
I think we can just disable it.

### CODE REVIEW

**Comment by itholic** [comment]
Oh I was also investigating this.

LGTM if test pass. Thanks :)

**Comment by HyukjinKwon** [comment]
+1. LGTM once the tests pass.

**Comment by ueshin** [comment]
Thanks! merging.

**Comment by HyukjinKwon** [comment]
@itholic I remember we had to add some additional dependencies and hacks because of `to_clipboard` in Github Actions. Can you take a look and clean up?

**Comment by itholic** [comment]
@HyukjinKwon Sure, let me take a look at this one.

**Pull request merged**
