### PR TITLE
DataFrame.cummin()

### PR DESCRIPTION
**Pull request by RainFung**
first cummin version base cummax

### CODE REVIEW

**Comment by yuwillrun** [comment]
Hello, @HyukjinKwon @ueshin . Travis CI raise error below
```
The command "if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then pip install -r requirements-dev.txt && pip list; else conda install -c conda-forge --yes --file requirements-dev.txt && conda list; fi" failed and exited with 1 during .
```

**Comment by HyukjinKwon** [comment]
Seems there's an issue at conda server side.

**Comment by yuwillrun** [comment]
Can you solve it ?

**Comment by HyukjinKwon** [comment]
It's not under my control .. let's wait for a bit before taking an action.

**Comment by HyukjinKwon** [comment]
@yuwillrun, can you sync with the master branch? https://github.com/databricks/koalas/commit/a96c01ffd026ccb213bf88c8e9e7f23a4b735d9e fixed the build

**Comment by HyukjinKwon** [comment]
Im going to take this over at https://github.com/databricks/koalas/pull/521

**Comment by RainFung** [comment]
Thanks for your carrying on working.

**Pull request closed without merging**
