### PR TITLE
Minor doc change for DataFrame.spark.checkpoint/DataFrame.spark.local_checkpoint

### PR DESCRIPTION
**Pull request by xinrong-databricks**

### CODE REVIEW

**Review by ueshin — APPROVED** [review]

**Comment by ueshin** [comment]
Thanks! merging.

**Comment by xinrong-databricks** [comment]
@ueshin Thank you!

**Comment by HyukjinKwon** [comment]
Thanks :-)

**Comment by xinrong-databricks** [comment]
@HyukjinKwon Thanks for catching this :)!

**Pull request merged**
