### PR TITLE
Add tests for non-string names

### PR DESCRIPTION
**Pull request by xinrong-databricks**

### CODE REVIEW

**Review by ueshin — APPROVED** [review]
LGTM.

**Comment by ueshin** [comment]
Thanks! merging.

**Comment by xinrong-databricks** [comment]
@ueshin Thanks for reviewing and merging it!

**Comment by HyukjinKwon** [comment]
Awesome!

**Comment by xinrong-databricks** [comment]
@HyukjinKwon Thank you!

**Comment by itholic** [comment]
Nice work 👍

**Pull request merged**
