### PR TITLE
Add the base for expanding and rolling in Series, Frame, SeriesGroupby and FrameGroupby

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR adds:

- Missing mechanism for expanding and rolling in Seres, Frame, SeriesGroupby and FrameGroupby
- Add the documentation base for expanding and rolling

by mimicking pandas class structure.

Partially addresses #807

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Oh sure. Will do.

**Comment by HyukjinKwon** [comment]
Thanks @ueshin ! merged.

**Comment by ueshin** [comment]
Sorry that I didn't make clear. Actually we need to the classes too. #855

**Comment by HyukjinKwon** [comment]
Thanks!

**Comment by ppakawatk** [comment]
Hi, 

Does the mechanism for aggregating (e.g. mean) after rolling being added sir?
I'm using Koalas 0.20, and getting this "
PandasNotImplementedError: The method `pandas.core.window.Rolling.mean()` is not implemented yet.".

**Comment by HyukjinKwon** [comment]
It's not implemented yet. These will be implemented in the near future.

**Pull request merged**
