### PR TITLE
[MINOR] Fix typos from 'Koala' to 'Koalas' in Series and DataFrame

### PR DESCRIPTION
**Pull request by ktksq**
DataFrame:

スクリーンショット 2019-11-06 1 35 22

Series:

スクリーンショット 2019-11-06 10 54 29

### CODE REVIEW

**Comment by ueshin** [comment]
@ktksq Good catch!
Seems like one more place we say `Koala` instead of `Koalas` in `series.py`.
Could you also fix it please? Thanks!

**Comment by ktksq** [comment]
@ueshin   I got it. Then i will fix all "koala"!🐨🐨

**Comment by ktksq** [comment]
スクリーンショット 2019-11-06 10 54 29

**Comment by HyukjinKwon** [comment]
Thanks for working on this @ktksq. Merged

**Pull request merged**
