### PR TITLE
Upgrade PySpark version to 2.4.7 for CI.

### PR DESCRIPTION
**Pull request by ueshin**
As PySpark 2.4.7 was released, this upgrades PySpark version to 2.4.7 for CI.

### CODE REVIEW

**Comment by ueshin** [comment]
PySpark 2.4.7 is not yet uploaded to any conda repository. Let's see.

**Review by HyukjinKwon — APPROVED** [review]
LGTM once tests pass

**Comment by itholic** [comment]
> PySpark 2.4.7 is not yet uploaded to any conda repository. Let's see.

LGTM except above 👍

**Review by itholic — APPROVED** [review]

**Comment by ueshin** [comment]
Changed to install PySpark 2.4.7 with `pip` as it seems not uploaded to `conda-forge`.

**Review by HyukjinKwon — APPROVED** [review]

**Pull request merged**
